// src/config/miniGames.ts

import { markRaw } from 'vue';
import type { MiniGame } from '@/types/minigame';
import {
  SlingShot,
  FruitSlice,
  WhackAMole,
  SkewerMaster,
  RhythmTap,
  PowerGauge,
  SpeedClick,
  ReactionTest,
  CatchBall,
  ArrowDash,
  NumberMatch,
  FindPair,
  MemorySequence,
  ColorWord,
  QuickMath,
  PatternCopy,
  HiddenObject,
  SlidePuzzle,
  BombDefuse,
  DodgeIt,
  LadderClimb,
  MazeEscape,
  StarGather,
  JumpUp,
  SpeedRun,
  DrawLine,
  RotateObject,
  SizeMatch,
  BalanceIt,
  SortIt
} from '@/components/minigames';

/**
 * 30개 미니게임 정의 - 모두 구현 완료!
 */

/**
 * 전체 미니게임 목록
 */
export const MINI_GAMES: MiniGame[] = [
  // 🎯 반사신경/타이밍 게임 (1-10)
  {
    id: 1,
    name: '새총 쏘기',
    nameEn: 'Slingshot Strike',
    category: 'action',
    instruction: '새총으로 쏘세요!',
    instructionEmoji: '🪨',
    scoreType: 'count',
    baseTimeLimit: 10,
    baseTargetScore: 60,
    component: markRaw(SlingShot),
    difficulty: 1,
  },
  {
    id: 2,
    name: '과일 자르기',
    nameEn: 'Slice the Fruits',
    category: 'action',
    instruction: '과일을 자르세요!',
    instructionEmoji: '🍎',
    scoreType: 'count',
    baseTimeLimit: 10,
    baseTargetScore: 50,
    component: markRaw(FruitSlice),
    difficulty: 2,
  },
  {
    id: 3,
    name: '두더지 잡기',
    nameEn: 'Whack a Mole',
    category: 'action',
    instruction: '두더지를 잡으세요!',
    instructionEmoji: '🐹',
    scoreType: 'count',
    baseTimeLimit: 10,
    baseTargetScore: 40,
    component: markRaw(WhackAMole),
    difficulty: 1,
  },
  {
    id: 4,
    name: '꼬치 만들기',
    nameEn: 'Skewer Master',
    category: 'timing',
    instruction: '꼬치를 만들어라!',
    instructionEmoji: '🍢',
    scoreType: 'count',
    baseTimeLimit: 12,
    baseTargetScore: 60,
    component: markRaw(SkewerMaster),
    difficulty: 2,
  },
  {
    id: 5,
    name: '리듬 탭',
    nameEn: 'Rhythm Tap',
    category: 'timing',
    instruction: '박자에 맞춰 탭!',
    instructionEmoji: '🎵',
    scoreType: 'accuracy',
    baseTimeLimit: 15,
    baseTargetScore: 80,
    component: markRaw(RhythmTap),
    difficulty: 3,
  },
  {
    id: 6,
    name: '파워 게이지',
    nameEn: 'Power Gauge',
    category: 'timing',
    instruction: '타이밍에 맞춰 놓으세요!',
    instructionEmoji: '💪',
    scoreType: 'accuracy',
    baseTimeLimit: 10,
    baseTargetScore: 70,
    component: markRaw(PowerGauge),
    difficulty: 2,
  },
  {
    id: 7,
    name: '빠른 클릭',
    nameEn: 'Fast Click',
    category: 'action',
    instruction: '빠르게 클릭하세요!',
    instructionEmoji: '👆',
    scoreType: 'count',
    baseTimeLimit: 5,
    baseTargetScore: 50,
    component: markRaw(SpeedClick),
    difficulty: 1,
  },
  {
    id: 8,
    name: '반응 테스트',
    nameEn: 'Reaction Test',
    category: 'timing',
    instruction: '신호가 뜨면 탭!',
    instructionEmoji: '⚡',
    scoreType: 'speed',
    baseTimeLimit: 10,
    baseTargetScore: 150,
    component: markRaw(ReactionTest),
    difficulty: 2,
  },
  {
    id: 9,
    name: '공 받기',
    nameEn: 'Catch the Ball',
    category: 'action',
    instruction: '공을 받으세요!',
    instructionEmoji: '⚾',
    scoreType: 'count',
    baseTimeLimit: 12,
    baseTargetScore: 45,
    component: markRaw(CatchBall),
    difficulty: 2,
  },
  {
    id: 10,
    name: '화살표 돌진',
    nameEn: 'Arrow Dash',
    category: 'action',
    instruction: '화살표 방향으로 스와이프!',
    instructionEmoji: '➡️',
    scoreType: 'speed',
    baseTimeLimit: 12,
    baseTargetScore: 90,
    component: markRaw(ArrowDash),
    difficulty: 3,
  },

  // 🧩 퍼즐/인지 게임 (11-18)
  {
    id: 11,
    name: '숫자 맞추기',
    nameEn: 'Number Match',
    category: 'puzzle',
    instruction: '같은 숫자를 찾으세요!',
    instructionEmoji: '🔢',
    scoreType: 'accuracy',
    baseTimeLimit: 10,
    baseTargetScore: 80,
    component: markRaw(NumberMatch),
    difficulty: 2,
  },
  {
    id: 12,
    name: '같은 그림 찾기',
    nameEn: 'Memory Match',
    category: 'memory',
    instruction: '같은 그림을 찾으세요!',
    instructionEmoji: '🃏',
    scoreType: 'speed',
    baseTimeLimit: 15,
    baseTargetScore: 100,
    component: markRaw(FindPair),
    difficulty: 3,
  },
  {
    id: 13,
    name: '순서 기억',
    nameEn: 'Remember Sequence',
    category: 'memory',
    instruction: '순서를 기억하세요!',
    instructionEmoji: '🧠',
    scoreType: 'accuracy',
    baseTimeLimit: 20,
    baseTargetScore: 100,
    component: markRaw(MemorySequence),
    difficulty: 4,
  },
  {
    id: 14,
    name: '색깔 이름',
    nameEn: 'Color Name',
    category: 'puzzle',
    instruction: '색 이름을 맞히세요!',
    instructionEmoji: '🌈',
    scoreType: 'accuracy',
    baseTimeLimit: 10,
    baseTargetScore: 70,
    component: markRaw(ColorWord),
    difficulty: 3,
  },
  {
    id: 15,
    name: '빠른 계산',
    nameEn: 'Quick Math',
    category: 'puzzle',
    instruction: '계산하세요!',
    instructionEmoji: '➕',
    scoreType: 'speed',
    baseTimeLimit: 12,
    baseTargetScore: 80,
    component: markRaw(QuickMath),
    difficulty: 3,
  },
  {
    id: 16,
    name: '패턴 따라하기',
    nameEn: 'Follow Pattern',
    category: 'memory',
    instruction: '패턴을 따라하세요!',
    instructionEmoji: '🔲',
    scoreType: 'accuracy',
    baseTimeLimit: 15,
    baseTargetScore: 100,
    component: markRaw(PatternCopy),
    difficulty: 3,
  },
  {
    id: 17,
    name: '숨은 그림',
    nameEn: 'Find Hidden',
    category: 'puzzle',
    instruction: '숨은 그림을 찾으세요!',
    instructionEmoji: '🔍',
    scoreType: 'speed',
    baseTimeLimit: 10,
    baseTargetScore: 100,
    component: markRaw(HiddenObject),
    difficulty: 2,
  },
  {
    id: 18,
    name: '퍼즐 슬라이드',
    nameEn: 'Slide Puzzle',
    category: 'puzzle',
    instruction: '퍼즐을 완성하세요!',
    instructionEmoji: '🧩',
    scoreType: 'speed',
    baseTimeLimit: 20,
    baseTargetScore: 150,
    component: markRaw(SlidePuzzle),
    difficulty: 4,
  },

  // 🏃 액션/수집 게임 (19-25)
  {
    id: 19,
    name: '폭탄 해제',
    nameEn: 'Bomb Defuse',
    category: 'puzzle',
    instruction: '와이어를 순서대로 잘라라!',
    instructionEmoji: '💣',
    scoreType: 'count',
    baseTimeLimit: 10,
    baseTargetScore: 50,
    component: markRaw(BombDefuse),
    difficulty: 1,
  },
  {
    id: 20,
    name: '장애물 피하기',
    nameEn: 'Avoid Obstacles',
    category: 'action',
    instruction: '장애물을 피하세요!',
    instructionEmoji: '🚧',
    scoreType: 'hybrid',
    baseTimeLimit: 15,
    baseTargetScore: 100,
    component: markRaw(DodgeIt),
    difficulty: 3,
  },
  {
    id: 21,
    name: '사다리 오르기',
    nameEn: 'Climb Ladder',
    category: 'action',
    instruction: '사다리를 오르세요!',
    instructionEmoji: '🪜',
    scoreType: 'speed',
    baseTimeLimit: 12,
    baseTargetScore: 120,
    component: markRaw(LadderClimb),
    difficulty: 2,
  },
  {
    id: 22,
    name: '미로 탈출',
    nameEn: 'Escape Maze',
    category: 'puzzle',
    instruction: '미로를 탈출하세요!',
    instructionEmoji: '🌀',
    scoreType: 'speed',
    baseTimeLimit: 15,
    baseTargetScore: 150,
    component: markRaw(MazeEscape),
    difficulty: 4,
  },
  {
    id: 23,
    name: '별 수집',
    nameEn: 'Star Collection',
    category: 'collection',
    instruction: '별을 모으세요!',
    instructionEmoji: '⭐',
    scoreType: 'count',
    baseTimeLimit: 10,
    baseTargetScore: 45,
    component: markRaw(StarGather),
    difficulty: 2,
  },
  {
    id: 24,
    name: '점프 게임',
    nameEn: 'Jump Game',
    category: 'timing',
    instruction: '장애물을 뛰어넘으세요!',
    instructionEmoji: '🦘',
    scoreType: 'hybrid',
    baseTimeLimit: 15,
    baseTargetScore: 80,
    component: markRaw(JumpUp),
    difficulty: 3,
  },
  {
    id: 25,
    name: '스피드 런',
    nameEn: 'Speed Run',
    category: 'action',
    instruction: '빠르게 달리세요!',
    instructionEmoji: '🏃',
    scoreType: 'speed',
    baseTimeLimit: 10,
    baseTargetScore: 100,
    component: markRaw(SpeedRun),
    difficulty: 2,
  },

  // 🎨 그리기/조작 게임 (26-30)
  {
    id: 26,
    name: '선 긋기',
    nameEn: 'Draw Line',
    category: 'precision',
    instruction: '선을 그으세요!',
    instructionEmoji: '✏️',
    scoreType: 'accuracy',
    baseTimeLimit: 10,
    baseTargetScore: 80,
    component: markRaw(DrawLine),
    difficulty: 2,
  },
  {
    id: 27,
    name: '물체 회전',
    nameEn: 'Rotate Object',
    category: 'precision',
    instruction: '물체를 빠르게 회전시켜 맞추세요!',
    instructionEmoji: '🔄',
    scoreType: 'accuracy',
    baseTimeLimit: 15,
    baseTargetScore: 50,
    component: markRaw(RotateObject),
    difficulty: 3,
  },
  {
    id: 28,
    name: '크기 맞추기',
    nameEn: 'Size Match',
    category: 'precision',
    instruction: '크기를 맞추세요!',
    instructionEmoji: '📏',
    scoreType: 'accuracy',
    baseTimeLimit: 10,
    baseTargetScore: 80,
    component: markRaw(SizeMatch),
    difficulty: 2,
  },
  {
    id: 29,
    name: '균형 잡기',
    nameEn: 'Keep Balance',
    category: 'precision',
    instruction: '균형을 잡으세요!',
    instructionEmoji: '⚖️',
    scoreType: 'hybrid',
    baseTimeLimit: 15,
    baseTargetScore: 100,
    component: markRaw(BalanceIt),
    difficulty: 4,
  },
  {
    id: 30,
    name: '순서 나열',
    nameEn: 'Sort Order',
    category: 'puzzle',
    instruction: '순서대로 나열하세요!',
    instructionEmoji: '🔢',
    scoreType: 'speed',
    baseTimeLimit: 12,
    baseTargetScore: 100,
    component: markRaw(SortIt),
    difficulty: 3,
  },
];

/**
 * ID로 미니게임 찾기
 */
export function getMiniGameById(id: number): MiniGame | undefined {
  return MINI_GAMES.find(game => game.id === id);
}

/**
 * 카테고리별 미니게임 가져오기
 */
export function getMiniGamesByCategory(category: string): MiniGame[] {
  return MINI_GAMES.filter(game => game.category === category);
}

/**
 * 난이도별 미니게임 가져오기
 */
export function getMiniGamesByDifficulty(difficulty: number): MiniGame[] {
  return MINI_GAMES.filter(game => game.difficulty === difficulty);
}

/**
 * 랜덤 미니게임 섞기
 */
export function getShuffledMiniGames(): MiniGame[] {
  const shuffled = [...MINI_GAMES];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j]!, shuffled[i]!];
  }
  return shuffled;
}
